server:
  port: 5000
  shutdown: graceful
  error:
    include-stacktrace: never

spring:
  application:
    name: config
  datasource:
    url: jdbc:mysql://localhost:3306/dev_config
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
